apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kafka
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics 
      interval: 15s